### ISSUE TITLE
Question/Answer list

### ISSUE THREAD

**Issue by badabam** [badabam/flashcards-react#1]
## Value statement
As a **student** 
I need **a list of learning cards** 
so that **I can improve my knowledge about programming** 

## Description (Text, Scribble, Wireframe, Design)
![question-answer-list](https://user-images.githubusercontent.com/157286/91669720-7224a200-eb17-11ea-8f6c-a80ea8fa9d66.png)

## Acceptance criteria
- [ ] Question and answer are both always visible

## Tasks
- [ ] Create feature branch
- [ ] Create QuizCard component in Storybook
- [ ] Write component tests
- [ ] Add components to app (feature implementation with state)
- [ ] Add missing styles
- [ ] Write integration tests w/ Cypress

## Complexity
low

**Comment by annettevogt** [comment]
> ## Value statement
> 
> As a **student**
> I need **a list of learning cards**
> so that **I can improve my knowledge about programming**
> ## Description (Text, Scribble, Wireframe, Design)
> 
>     * It's a long scrolling list of cards
> 
>     * A card contains a question and an answer
> 
> 
> ## Acceptance criteria
> 
>     * [ ]  Cards have to be visually separated
> 
>     * [ ]  Question and answer are simple text in a good readable size
> 
>     * [ ]  Question and answer are both always visible
> 
>     * [ ]  Cards are scrolled vertically
> 
> 
> ## Tasks
> 
>     * [ ]  Create feature branch
> 
>     * [ ]  Create components (component names go here) in Storybook
> 
>     * [ ]  Write component tests
> 
>     * [ ]  Add components to app (feature implementation with state)
> 
>     * [ ]  Add missing styles
> 
>     * [ ]  Write integration tests w/ Cypress
> 
> 
> ## Size
> 
> small
