### ISSUE TITLE
Toggle answer

### ISSUE THREAD

**Issue by badabam** [badabam/flashcards-react#2]
## Value statement - a requirement, not a solution
As a **student** 
I need **to not see the answer before I want to** 
so that **I don't get spoiled** 

## Description (Text, Scribble, Wireframe, Design)
![toggle-answer](https://user-images.githubusercontent.com/157286/91669763-dba4b080-eb17-11ea-8e54-d10ed632dbfb.png)

## Acceptance criteria
- [ ] Answer is hidden by default
- [ ] Button text changes on tap
- [ ] Each cards expands in place
- [ ] Card expansion is animated

## Tasks
- [ ] Create button component
- [ ] Add toggle logic
- [ ] Finish styling
- [ ] Test with a few cards on mobile and desktop

## Size
medium
