### ISSUE TITLE
Bookmarking

### ISSUE THREAD

**Issue by badabam** [badabam/flashcards-react#3]
## Value statement
As a **student** 
I need **to bookmark cards** 
so that **I can quickly find the ones I need to practice** 

## Description (Text, Scribble, Wireframe, Design)
![bookmarking](https://user-images.githubusercontent.com/157286/91669786-0f7fd600-eb18-11ea-91c1-b3bb17859ba0.png)

## Acceptance criteria
- [ ] Bookmark has two different colors to toggle (see design)
- [ ] Bookmark toggles on click

## Tasks
- [ ] Create Bookmark component
- [ ] Add styling
- [ ] Add toggle logic
- [ ] Test on Desktop and Browser

## Complexity
low
