### ISSUE TITLE
Bookmark filter

### ISSUE THREAD

**Issue by badabam** [badabam/flashcards-react#4]
## Value statement
As a **student** 
I need **a way to just see bookmarked cards** 
so that **there is less visual clutter to find the relevant cards** 

## Description (Text, Scribble, Wireframe, Design)
![bookmark-filter](https://user-images.githubusercontent.com/157286/91669813-43f39200-eb18-11ea-83b9-661546232602.png)

## Acceptance criteria
- [ ] Link text toggles
- [ ] Bookmarked / all cards are toggled with link

## Tasks
- [ ] Create or use a Link (or Button) component
- [ ] Add state "isOnlyBookmarksShown"

## Complexity
medium
