### ISSUE TITLE
Add question

### ISSUE THREAD

**Issue by badabam** [badabam/flashcards-react#5]
## Value statement
As a **student or content creator** 
I need **to add new cards** 
so that **I can learn even more** 

## Description (Text, Scribble, Wireframe, Design)
![add-question](https://user-images.githubusercontent.com/157286/91669864-afd5fa80-eb18-11ea-8769-49ec4cfff24a.png)

## Acceptance criteria
- [ ] The card list has a button "Add question" at the bottom that links to `/create`
- [ ] The form is found at the path `/create`
- [ ] The button is disabled until both inputs are filled
- [ ] The form reacts on submit (Enter key or button press)
- [ ] The first input has focus at start and after submit
- [ ] The form is cleared after submit
- [ ] The new card is added at the end

## Tasks
- [ ] Add routing
- [ ] Create form component
- [ ] Add styling
- [ ] Test on mobile and desktop

## Complexity
large
