### ISSUE TITLE
Save state locally

### ISSUE THREAD

**Issue by badabam** [badabam/flashcards-react#6]
## Value statement - a requirement, not a solution
As a **student** 
I need **to keep my bookmarks through sessions** 
so that **I don't loose my valuable customizations** 

## Description (Text, Scribble, Wireframe, Design)
- No visible impact

## Acceptance criteria
- [ ] every change on the state `cards` should trigger a save to localStorage
- [ ] Reload of the page should load `cards` from localStorage

## Tasks
- [ ] Create services for localStorage
- [ ] Implement save/load for `cards`
- [ ] Test on desktop and mobile

## Complexity
medium
